name: Check Build Status

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check_build_status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Build Status
      id: get-build-status
      uses: actions/github-script@v6
      with:
        script: |
          const fetch = require('node-fetch');
          const response = await fetch('http://localhost:9111/buildConfiguration/TweetTrendNew_Build/106?expandBuildChangesSection=true&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false');
          const data = await response.json();
          console.log('Build status:', data.status);
          return data.status;

    - name: Fail or Pass PR Based on Build Status
      id: evaluate-status
      run: |
        STATUS="${{ steps.get-build-status.outputs.result }}"
        
        if [ "$STATUS" != "SUCCESS" ]; then
          echo "Build status is not successful. Failing the workflow."
          exit 1
        fi
        echo "Build status is successful. Proceeding."

    - name: Create Pull Request
      if: ${{ steps.evaluate-status.outcome == 'success' }}
      uses: actions/github-script@v6


      with:
        script: |
          const octokit = require('@actions/github').getOctokit(process.env.GITHUB_TOKEN);
          const { data: pullRequest } = await octokit.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Pull Request Title',
            head: context.ref,
            base: 'main',
            body: 'Pull Request Body'
          });
          console.log(`Pull request created: ${pullRequest.html_url}`);
